/**
 * The public interface of the library. Everything else under lib/ is its
 * implementation and may change in any release: the in-place helpers the
 * operations are built from, the date conversions of the serialisation,
 * and the general utilities.
 */
export type { WithId, WithNote, WithType } from './shared/utils.js'
export * from './model/Quantity.js'
export * from './model/Agent.js'
export * from './model/Assumption.js'
export * from './model/ConditionState.js'
export * from './model/Symbol.js'
export * from './model/Feature.js'
export * from './model/Edit.js'
export * from './model/Version.js'
export * from './collation/Collation.js'
export * from './model/TrackCalibration.js'
export * from './systems/TrackerBar.js'
export * from './systems/welteT100/bar.js'
export * from './systems/welteLicensee/bar.js'
export * from './systems/welteT98/bar.js'
export * from './systems/index.js'
export * from './systems/ReproducingSystem.js'
export * from './model/FeatureSource.js'
export * from './model/Perforator.js'
export * from './model/RollCopy.js'
export * from './model/procedures.js'
export * from './model/vocabulary.js'
export * from './analysis/reservations.js'
export * from './analysis/witnesses.js'
export { alignFeatures, tooShortToShorten, type AlignmentResult } from './collation/alignment.js'
export * from './collation/statistics.js'
export * from './model/Edition.js'
export * from './view/EditionView.js'
export * from './analysis/ownPaper.js'
export * from './emulation/negotiation.js'
export * from './collation/scatter.js'
export * from './ops/index.js'
export * from './emulation/Emulation.js'
export * from './validate.js'
export * from './analysis/constraints.js'
export * from './collation/substitution.js'
export * from './io/context.js'
export * from './analysis/sigla.js'
export * from './model/notes.js'
export { asJsonLd } from './io/asJsonLd.js'
export { importJsonLd } from './io/importJsonLd.js'
export { formatVersion, migrate } from './io/migrate.js'
export { readFromStanfordAton, type StanfordAtonOptions } from './readers/stanfordAton.js'
export { readFromPhillipsEroll, CONTROL_OFFSET, phillipsSystems, type PhillipsErollOptions } from './readers/phillipsEroll.js'
export { readFromSpencerBar, readSpencerAnn, paperSpeedOfSpencerAnn, SPENCER_ROWS_PER_INCH, type SpencerBarOptions } from './readers/spencerBar.js'
